DUNGEONS = {
    "town": {
        "display_name": "町",
        "area_level": 1,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "town",
        "next_dungeon_key": "forest",
    },
    "grassland": {
        "display_name": "草原",
        "area_level": 2,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "grassland",
        "next_dungeon_key": "village",
    },
    "forest": {
        "display_name": "森",
        "area_level": 3,
        "description": "中級者向けのダンジョン",
        "dungeon_key": "forest",
        "next_dungeon_key": "graveyard",
    },
    "village": {
        "display_name": "集落",
        "area_level": 4,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "village",
        "next_dungeon_key": "forest",
    },
    "graveyard": {
        "display_name": "墓地",
        "area_level": 5,
        "description": "上級者向けのダンジョン",
        "dungeon_key": "graveyard",
        "next_dungeon_key": "ruins",
    },
    "ruins": {
        "display_name": "遺跡",
        "area_level": 6,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "ruins",
        "next_dungeon_key": "castle",
    },
    "castle": {
        "display_name": "古城",
        "area_level": 7,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "castle",
        "next_dungeon_key": "volcano",
    },
    "volcano": {
        "display_name": "火山",
        "area_level": 8,
        "description": "初心者向けのダンジョン",
        "dungeon_key": "volcano",
        "next_dungeon_key": "end",
    },
}
